app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from erik.dsmtw import DeSlimsteMens

socketio = SocketIO()

def create_app(questions_directory, player_names, debug=False):
	global global_questions_directory # it's bad but at least I know it's bad
	global global_player_names

	"""Create an application."""
	app = Flask(__name__)
	app.debug = debug
	app.config['SECRET_KEY'] = 'miep'
	app.config['questions_directory'] = questions_directory
	app.config['game'] = DeSlimsteMens(player_names, questions_directory)

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint, url_prefix='')

	socketio.init_app(app)
	return app

app/main/__init__.py
from flask import Blueprint

from . import events

main = Blueprint('main', __name__, template_folder='../templates', static_folder='../static')

from . import routes

app/main/routes.py
import os
import random

from flask import session, redirect, url_for, render_template, request, send_file
from . import main

from flask import current_app

@main.route('/')
def landing():
	return render_template('landing.html', global_questions_directory=current_app.config["questions_directory"])

@main.route('/host')
def host(callback=None):
	return render_template('game.html', host=True)

@main.route('/player')
def player(callback=None):
	return render_template('game.html', host=False)

@main.route('/resources/<string:filename>')
def display_label_image(filename):
	global_questions_directory = current_app.config["questions_directory"]

	if not os.path.isabs(global_questions_directory):
		path = os.path.join("..", global_questions_directory, filename)
	else:
		path = os.path.join(global_questions_directory, filename)

	return send_file(path)

app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>De Slimste Mens Ter Wereld</title>

		<script src="/static/js/socket.io.js"></script>

		<!-- Bootstrap -->
		<!-- after all, why wouldn't I? -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="/static/css/style.css">

		<!-- Round-specific styles -->
		<link rel="stylesheet" type="text/css" href="/static/css/rounds/369.css">
		<link rel="stylesheet" type="text/css" href="/static/css/rounds/OpenDeur.css">
		<link rel="stylesheet" type="text/css" href="/static/css/rounds/Puzzel.css">
		<link rel="stylesheet" type="text/css" href="/static/css/rounds/Galerij.css">
		<link rel="stylesheet" type="text/css" href="/static/css/rounds/CollectiefGeheugen.css">
		<link rel="stylesheet" type="text/css" href="/static/css/rounds/Finale.css">

		<!-- Third-party styles -->
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="charset" content="UTF-8">
	</head>
	<body>
		{% block content %}
		{% endblock %}
	</body>

	<script src="/static/js/gameshow.js"></script>
	<script src="/static/js/misc/scores.js"></script>
	<script src="/static/js/misc/AuxiliaryMedia.js"></script>
	<script src="/static/js/misc/Answers.js"></script>
	<script src="/static/js/misc/Timer.js"></script>
	<script src="/static/js/misc/Bumper.js"></script>
	<script src="/static/js/misc/Sound.js"></script>
	<script src="/static/js/dsmtw.js"></script>
</html>

app/templates/game.html
{% extends "base.html" %}
{% block content %}
	{% if host %}
		{% include "host.html" %}
	{% else %}
		{% include "player.html" %}
	{% endif %}
	<div id="bumper" class="d-none">
		<h1 id="bumper_text">Wie dit leest, is zot</h1>
	</div>
	<div class="container-fluid {% if not host %}client{% endif %}">
		<div class="host" style="position: fixed; top: 0; top: 0; left: 0; right: 0;">
			<button onclick="javascript:dsmtw.advanceRound();">Advance round</button>
			<button onclick="javascript:dsmtw.correct();">Correct</button>
			<button onclick="javascript:dsmtw.pass();">Pass</button>
			<button onclick="javascript:dsmtw.clockStart();">Clock start</button>
			<button onclick="javascript:dsmtw.clockStop();">Clock stop</button>
			<h1 id="currentround" style="display: inline-block;">current round</h1>
		</div>
		<button class="float host" onclick="javascript:dsmtw.releaseAdvance();">></button>
		<div class="row full top align-items-center justify-content-center text-center">
			<!-- Scores will go here -->
			<div class="col-2" style="max-width: 350px;">
				<div class="scores" id="scores">
					<!-- Score badges will be generated automatically -->
				</div>
				<div>
					<button class="clocktoggle host"
							onclick="javascript:dsmtw.clockToggle();"
							id="button_clock_toggle">Start klok</button>
				</div>
			</div>
			<!-- Actual game content will go here -->
			<div class="col-10 game">
				<div id="container_auxiliaryMedia" class="row justify-content-center pb-4 auxiliaryMedia">
					<div class="col-4 text-center">
						<img id="auxiliaryMedia">
					</div>
				</div>
				<div id="round_start" class="round">
					<button onclick="javascript:dsmtw.startGame();" class="host">Start het spel</button>
				</div>
				{% include "rounds/369.html" %}
				{% include "rounds/OpenDeur.html" %}
				{% include "rounds/Puzzel.html" %}
				{% include "rounds/Galerij.html" %}
				{% include "rounds/CollectiefGeheugen.html" %}
				{% include "rounds/Finale.html" %}
			</div>
		</div>
	</div>
	<video id="auxiliaryMedia_video" class="d-none"></video>
	<audio id="snd_bumper">
  		<source src="/static/sounds/bumper.mp3" type="audio/mpeg">
	</audio>
	<audio id="snd_correct">
  		<source src="/static/sounds/correct.mp3" type="audio/mpeg">
	</audio>
	<audio id="snd_clock">
  		<source src="/static/sounds/clock.mp3" type="audio/mpeg">
	</audio>
	<audio id="snd_clock_end">
  		<source src="/static/sounds/clock_end.mp3" type="audio/mpeg">
	</audio>
	<audio id="snd_intro">
  		<source src="/static/sounds/intro.mp3" type="audio/mpeg">
	</audio>
	<audio id="snd_finale">
  		<source src="/static/sounds/finale.mp3" type="audio/mpeg">
	</audio>
{% endblock %}

app/templates/host.html
<script type="text/javascript">
	host = true;
</script>

app/templates/landing.html
{% extends "base.html" %}
{% block content %}
	<link rel="stylesheet" type="text/css" href="/static/css/landing.css">
	<div class="container-fluid text-center">
		<div class="row full align-items-center justify-content-center">
			<div class="col">
				<div id="title">
					<h1 id="title">De Slimste Mens Ter Wereld</h1>
					<img id="halo" src="/static/img/dsmtw_logo.png">
				</div>
				<p class="fs-2" id="attribution">door Anthe Sevenants</p>
				<div>
					<a class="button" href="{{ url_for('main.host') }}">Ik ben de presentator</a>
					<a class="button" href="{{ url_for('main.player') }}">Ik ben een speler</a>
				</div>
				<div class="fs-4 pt-4">De volgende vragenset is geladen: {{ global_questions_directory }}</div>
			</div>
		</div>
	</div>
{% endblock %}

app/templates/overview.html
{% extends "base.html" %}
{% block content %}
	<script type="text/javascript">
		host = true;
	</script>
	<div style="position: fixed; top: 0; top: 0; left: 0; right: 0;">
		<button onclick="javascript:dsmtw.advanceRound();">Advance round</button>
		<button onclick="javascript:dsmtw.correct();">Correct</button>
		<button onclick="javascript:dsmtw.pass();">Pass</button>
		<button onclick="javascript:dsmtw.clockStart();">Clock start</button>
		<button onclick="javascript:dsmtw.clockStop();">Clock stop</button>
		<h1 id="currentround" style="display: inline-block;">current round</h1>
	</div>
	<div class="container">
		<button class="float" onclick="javascript:dsmtw.releaseAdvance();">></button>
		<div class="row full top align-items-center justify-content-center text-center">
			<!-- Scores will go here -->
			<div class="col-2">
				<h3>Scores</h3>
				<div class="scores" id="scores">
					<!-- Score badges will be generated automatically -->
				</div>
				<div>
					<button class="clocktoggle"
							onclick="javascript:dsmtw.clockToggle();"
							id="button_clock_toggle">Start klok</button>
				</div>
			</div>
			<!-- Actual game content will go here -->
			<div class="col-10 game">
				<div id="container_auxiliaryMedia" class="row justify-content-center pb-4 auxiliaryMedia">
					<div class="col-4 text-center">
						<img id="auxiliaryMedia">
					</div>
				</div>
				{% include "rounds/369.html" %}
				{% include "rounds/OpenDeur.html" %}
				{% include "rounds/Puzzel.html" %}
				{% include "rounds/Galerij.html" %}
				{% include "rounds/CollectiefGeheugen.html" %}
				{% include "rounds/Finale.html" %}
			</div>
		</div>
	</div>
{% endblock %}

app/templates/player.html
<script type="text/javascript">
	host = false;
</script>

app/templates/rounds/369.html
<script src="/static/js/rounds/369.js"></script>
<div id="round_3-6-9" class="round">
	<div>
		<div class="host">
			<h4 id="round_3-6-9_question" class="question">Vraag</h4>
			<p id="round_3-6-9_answer" class="answer">Antwoord</p>
			<div class="controls">
				<button class="correct" onclick="javascript:dsmtw.correct();">Goed</button> <button onclick="javascript:dsmtw.pass();">Fout</button>
			</div>
		</div>
	</div>
	<div id="round_3-6-9_game_field">
		<div id="369_circle_0" class="ThreeSixNine circle transparent small" dsmtw-question-number="1">
			<p class="score" id="369_0">1</p>
			<div id="369_circlebackground_0" class="background"></div>
		</div>
		<div id="369_circle_1" class="ThreeSixNine circle transparent small" dsmtw-question-number="2">
			<p class="score" id="369_1">2</p>
			<div id="369_circlebackground_1" class="background"></div>
		</div>
		<div id="369_circle_2" class="ThreeSixNine circle transparent small raised" dsmtw-question-number="3">
			<p class="score" id="369_2">3</p>
			<div id="369_circlebackground_2" class="background"></div>
		</div>
		<div id="369_circle_3" class="ThreeSixNine circle transparent small" dsmtw-question-number="4">
			<p class="score" id="369_3">4</p>
			<div id="369_circlebackground_3" class="background"></div>
		</div>
		<div id="369_circle_4" class="ThreeSixNine circle transparent small" dsmtw-question-number="5">
			<p class="score" id="369_4">5</p>
			<div id="369_circlebackground_4" class="background"></div>
		</div>
		<div id="369_circle_5" class="ThreeSixNine circle transparent small raised" dsmtw-question-number="6">
			<p class="score" id="369_5">6</p>
			<div id="369_circlebackground_5" class="background"></div>
		</div>
		<div id="369_circle_6" class="ThreeSixNine circle transparent small" dsmtw-question-number="7">
			<p class="score" id="369_6">7</p>
			<div id="369_circlebackground_6" class="background"></div>
		</div>
		<div id="369_circle_7" class="ThreeSixNine circle transparent small" dsmtw-question-number="8">
			<p class="score" id="369_7">8</p>
			<div id="369_circlebackground_7" class="background"></div>
		</div>
		<div id="369_circle_8" class="ThreeSixNine circle transparent small raised" dsmtw-question-number="9">
			<p class="score" id="369_8">9</p>
			<div id="369_circlebackground_8" class="background"></div>
		</div>
		<div id="369_circle_9" class="ThreeSixNine circle transparent small" dsmtw-question-number="10">
			<p class="score" id="369_9">10</p>
			<div id="369_circlebackground_9" class="background"></div>
		</div>
		<div id="369_circle_10" class="ThreeSixNine circle transparent small" dsmtw-question-number="11">
			<p class="score" id="369_10">11</p>
			<div id="369_circlebackground_10" class="background"></div>
		</div>
		<div id="369_circle_11" class="ThreeSixNine circle transparent small raised" dsmtw-question-number="12">
			<p class="score" id="369_11">12</p>
			<div id="369_circlebackground_11" class="background"></div>
		</div>
		<div id="369_circle_12" class="ThreeSixNine circle transparent small" dsmtw-question-number="13">
			<p class="score" id="369_12">13</p>
			<div id="369_circlebackground_12" class="background"></div>
		</div>
		<div id="369_circle_13" class="ThreeSixNine circle transparent small" dsmtw-question-number="14">
			<p class="score" id="369_13">14</p>
			<div id="369_circlebackground_13" class="background"></div>
		</div>
		<div id="369_circle_14" class="ThreeSixNine circle transparent small raised" dsmtw-question-number="15">
			<p class="score" id="369_14">15</p>
			<div id="369_circlebackground_14" class="background"></div>
		</div>
	</div>
</div>

app/templates/rounds/CollectiefGeheugen.html
<script src="/static/js/rounds/CollectiefGeheugen.js"></script>
<div id="round_Collectief geheugen" class="round Collectief geheugen">
	<div id="round_Collectief geheugen_answers" class="row justify-content-center">
		<div class="col-4 answers">
			<p class="answer" onclick="">
				<span class="score" id="round_Collectief geheugen_answer_score_0"></span>
				<span class="text" id="round_Collectief geheugen_answer_0">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Collectief geheugen_answer_score_1"></span>
				<span class="text" id="round_Collectief geheugen_answer_1">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Collectief geheugen_answer_score_2"></span>
				<span class="text" id="round_Collectief geheugen_answer_2">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Collectief geheugen_answer_score_3"></span>
				<span class="text" id="round_Collectief geheugen_answer_3">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Collectief geheugen_answer_score_4"></span>
				<span class="text" id="round_Collectief geheugen_answer_4">Antwoord</span>
			</p>
		</div>
	</div>
</div>

app/templates/rounds/Finale.html
<script src="/static/js/rounds/Finale.js"></script>
<div id="round_Finale" class="round Finale">
	<div id="round_Finale_answers" class="row justify-content-center">
		<div class="host">
			<h4 id="round_Finale_question" class="question">Vraag</h4>
		</div>
		<div class="col-12 answers text-center">
			<p class="answer" onclick="">
				<span class="score" id="round_Finale_answer_score_0">20</span>
				<span class="text" id="round_Finale_answer_0">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Finale_answer_score_1">20</span>
				<span class="text" id="round_Finale_answer_1">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Finale_answer_score_2">20</span>
				<span class="text" id="round_Finale_answer_2">Antwoord</span>
			</p>
		</div>
		<div class="col-12 answers text-center">
			<p class="answer" onclick="">
				<span class="score" id="round_Finale_answer_score_3">20</span>
				<span class="text" id="round_Finale_answer_3">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Finale_answer_score_4">20</span>
				<span class="text" id="round_Finale_answer_4">Antwoord</span>
			</p>
		</div>
	</div>
</div>

app/templates/rounds/Galerij.html
<script src="/static/js/rounds/Galerij.js"></script>
<div id="round_Galerij" class="round Galerij">
	<div id="round_Galerij_slideshow_controls" class="host">
		<p id="round_Galerij_answer" class="answer">Antwoord</p>
		<button class="correct" id="round_Galerij_correct_button">Gevonden</button> 
		<button onclick="javascript:dsmtw.pass();">Pas</button>
	</div>
	<div id="round_Galerij_answers" class="row justify-content-center host">
		<div class="col-4 answers">
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_0">10</span>
				<span class="text" id="round_Galerij_answer_0">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_1">10</span>
				<span class="text" id="round_Galerij_answer_1">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_2">10</span>
				<span class="text" id="round_Galerij_answer_2">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_3">10</span>
				<span class="text" id="round_Galerij_answer_3">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_4">10</span>
				<span class="text" id="round_Galerij_answer_4">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_5">10</span>
				<span class="text" id="round_Galerij_answer_5">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_6">10</span>
				<span class="text" id="round_Galerij_answer_6">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_7">10</span>
				<span class="text" id="round_Galerij_answer_7">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_8">10</span>
				<span class="text" id="round_Galerij_answer_8">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Galerij_answer_score_9">10</span>
				<span class="text" id="round_Galerij_answer_9">Antwoord</span>
			</p>
		</div>
	</div>
</div>

app/templates/rounds/OpenDeur.html
<script src="/static/js/rounds/OpenDeur.js"></script>
<div id="round_Open deur" class="round OpenDeur">
	<div id="round_Open deur_questioneers" class="row">
	</div>
	<div id="round_Open deur_answers" class="row justify-content-center">
		<div class="host">
			<h4 id="round_Open deur_question" class="question">Vraag</h4>
		</div>
		<div class="col-4 answers">
			<p class="answer" onclick="">
				<span class="score" id="round_Open deur_answer_score_0">20</span>
				<span class="text" id="round_Open deur_answer_0">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Open deur_answer_score_1">20</span>
				<span class="text" id="round_Open deur_answer_1">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Open deur_answer_score_2">20</span>
				<span class="text" id="round_Open deur_answer_2">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Open deur_answer_score_3">20</span>
				<span class="text" id="round_Open deur_answer_3">Antwoord</span>
			</p>
		</div>
	</div>
</div>

app/templates/rounds/Puzzel.html
<script src="/static/js/rounds/Puzzel.js"></script>
<div id="round_Puzzel" class="round Puzzel">
	<div id="round_Puzzel_puzzle" class="row text-center justify-content-center pb-4">
		<div class="col-6">
			<table id="round_Puzzel_puzzle_table" cellpadding="25">
				<tr>
					<td id="round_Puzzel_puzzle_keyword_0">trefwoord 1</td>
					<td id="round_Puzzel_puzzle_keyword_1">trefwoord 2</td>
					<td id="round_Puzzel_puzzle_keyword_2">trefwoord 3</td>
				</tr>
				<tr>
					<td id="round_Puzzel_puzzle_keyword_3">trefwoord 4</td>
					<td id="round_Puzzel_puzzle_keyword_4">trefwoord 5</td>
					<td id="round_Puzzel_puzzle_keyword_5">trefwoord 6</td>
				</tr>
				<tr>
					<td id="round_Puzzel_puzzle_keyword_6">trefwoord 7</td>
					<td id="round_Puzzel_puzzle_keyword_7">trefwoord 8</td>
					<td id="round_Puzzel_puzzle_keyword_8">trefwoord 9</td>
				</tr>
				<tr>
					<td id="round_Puzzel_puzzle_keyword_9">trefwoord 10</td>
					<td id="round_Puzzel_puzzle_keyword_10">trefwoord 11</td>
					<td id="round_Puzzel_puzzle_keyword_11">trefwoord 12</td>
				</tr>
			</table>
		</div>
	</div>
	<div id="round_Puzzel_answers" class="row justify-content-center">
		<div class="col-4 answers">
			<p class="answer" onclick="">
				<span class="score" id="round_Puzzel_answer_score_0">30</span>
				<span class="text" id="round_Puzzel_answer_0">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Puzzel_answer_score_1">30</span>
				<span class="text" id="round_Puzzel_answer_1">Antwoord</span>
			</p>
			<p class="answer" onclick="">
				<span class="score" id="round_Puzzel_answer_score_2">30</span>
				<span class="text" id="round_Puzzel_answer_2">Antwoord</span>
			</p>
		</div>
	</div>
</div>